language: node_js
sudo: required
dist: trusty

git:
  # set a custom clone depth, so contributor data does not get lost
  # running "git fetch --unshallow" in before_install is also an option
  depth: 9999999

node_js:
  - "6"

addons:
  apt:
    packages:
      - nsis
      - ruby-dev

cache:
  apt: true
  directories:
    - "node_modules"
    - "bower_components"
    - "build/cache"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g bower grunt-cli"

install:
  - "npm install"

script:
  # test and build
  - grunt build:prod
  # compile and package
  - if [ -n "${TRAVIS_TAG}" ]; then rvm use --default 1.9.3; build/travis/package.sh; fi

deploy:
  - provider: releases
    api_key: "${RELEASES_API_KEY}"
    file: dist/*{.tar.gz,.zip,.exe,-checksums.txt}
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: node build/travis/update_release.js
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
  webhooks:
    urls:
      - "${WEBHOOK_GITTER}"
    on_success: change
    on_failure: always
    on_start: never
