language: node_js
sudo: required
dist: trusty

git:
  # set a custom clone depth, so contributor data does not get lost
  # running "git fetch --unshallow" in before_install is also an option
  depth: 9999999

node_js:
  - lts/*

addons:
  apt:
    packages:
      - nsis

cache:
  apt: true
  directories:
    - node_modules
    - build/cache
  yarn: true

before_install:
  - |
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
  - |
    set -e
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
    sudo apt-get update -qq && sudo apt-get install -qq -o=Dpkg::Use-Pty=0 -y yarn >/dev/null 2>/dev/null
    shopt -s expand_aliases
    alias yarn=/usr/bin/yarn
    yarn --version

install:
  - yarn global add --no-progress --non-interactive grunt-cli
  - yarn install --pure-lockfile --no-progress --non-interactive

script:
  # test and build
  - grunt build:prod:coverage
  - yarn run codecov
  # compile and package
  - if [ -n "${TRAVIS_TAG}" ]; then build/travis/package.sh; fi

deploy:
  - provider: releases
    api_key: "${RELEASES_API_KEY}"
    file: dist/*{.tar.gz,.zip,.exe,-checksums.txt}
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: node build/travis/update_release.js
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
  webhooks:
    urls:
      - "${WEBHOOK_GITTER}"
    on_success: change
    on_failure: always
    on_start: never
